// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBowQZnTwTGsVzomOkKrUTtUsB6oinaR5Y',
    appId: '1:580329183256:ios:a6f81e2452903ad1fb0b6d',
    messagingSenderId: '580329183256',
    projectId: 'project-ad-2026-4b28d',
    storageBucket: 'project-ad-2026-4b28d.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutterApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBowQZnTwTGsVzomOkKrUTtUsB6oinaR5Y',
    appId: '1:580329183256:ios:a6f81e2452903ad1fb0b6d',
    messagingSenderId: '580329183256',
    projectId: 'project-ad-2026-4b28d',
    storageBucket: 'project-ad-2026-4b28d.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYY1ChOJ6gdUqlBB45Aeu1e4Xhw8VicFY',
    appId: '1:580329183256:web:ac42ba635cf4bf09fb0b6d',
    messagingSenderId: '580329183256',
    projectId: 'project-ad-2026-4b28d',
    authDomain: 'project-ad-2026-4b28d.firebaseapp.com',
    storageBucket: 'project-ad-2026-4b28d.firebasestorage.app',
    measurementId: 'G-4CFD4Z9W6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvACk_6F3_dQtTQdUS7rmXVBXklrW048',
    appId: '1:580329183256:android:0fb210dd7b78e1d0fb0b6d',
    messagingSenderId: '580329183256',
    projectId: 'project-ad-2026-4b28d',
    storageBucket: 'project-ad-2026-4b28d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYY1ChOJ6gdUqlBB45Aeu1e4Xhw8VicFY',
    appId: '1:580329183256:web:be44be44bb43befcfb0b6d',
    messagingSenderId: '580329183256',
    projectId: 'project-ad-2026-4b28d',
    authDomain: 'project-ad-2026-4b28d.firebaseapp.com',
    storageBucket: 'project-ad-2026-4b28d.firebasestorage.app',
    measurementId: 'G-J55RZTWWDJ',
  );
}
