// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8hRDwmTUFxl_zPoPbm2xflSoclWSxH80',
    appId: '1:677742863763:web:f2cb02a24ab1cbc509f466',
    messagingSenderId: '677742863763',
    projectId: 'tadika-62f76',
    authDomain: 'tadika-62f76.firebaseapp.com',
    storageBucket: 'tadika-62f76.firebasestorage.app',
    measurementId: 'G-RH66823P64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1_5ZaL2Ab5zkFc7gBtxekA_FwQhm5Lc',
    appId: '1:677742863763:android:d99b4fa6da99693209f466',
    messagingSenderId: '677742863763',
    projectId: 'tadika-62f76',
    storageBucket: 'tadika-62f76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHeMRSrI4tKHYwSQP4AXRucFzw9SHjSMQ',
    appId: '1:677742863763:ios:e04424dcb78f5c9009f466',
    messagingSenderId: '677742863763',
    projectId: 'tadika-62f76',
    storageBucket: 'tadika-62f76.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHeMRSrI4tKHYwSQP4AXRucFzw9SHjSMQ',
    appId: '1:677742863763:ios:e04424dcb78f5c9009f466',
    messagingSenderId: '677742863763',
    projectId: 'tadika-62f76',
    storageBucket: 'tadika-62f76.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8hRDwmTUFxl_zPoPbm2xflSoclWSxH80',
    appId: '1:677742863763:web:d94d8ef7b172ffc309f466',
    messagingSenderId: '677742863763',
    projectId: 'tadika-62f76',
    authDomain: 'tadika-62f76.firebaseapp.com',
    storageBucket: 'tadika-62f76.firebasestorage.app',
    measurementId: 'G-LHY99D0ZVC',
  );
}